backend:
  name: auth0
  auth0_domain: "dev-cm8742hgumkgiavt.us.auth0.com"
  auth0_client_id: "kQxVL3qaMEy1rpRPvhpRnQVQOncsWXO1"
  auth0_callback_url: "https://svm-site.netlify.app/admin/callback"

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "news"
    label: "Obavijesti"
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Sadr≈æaj", name: "body", widget: "markdown" }
